### ISSUE TITLE
2 links

### ISSUE THREAD

**Issue by jordikruit** [marnixah/japanese-asmr-parser#2]
https://japaneseasmr.com/54005/

**Comment by marnixah** [comment]
@fredi-68 please assign proper labels

**Comment by marnixah** [comment]
@jordikruit in the example you gave has only 0.5MiB difference in audio files(both 159MiB). I'll continue assuming this is intended, but if it is not. Please do say so

**Comment by marnixah** [comment]
Should 🤞 be fixed with commit 3eb9350d5ee87822c64f54e99dcf3a421a3a9426. If it's not feel free to re-open the issue

**Comment by fredi-68** [comment]
> @fredi-68 please assign proper labels

me looking for the person who asked (he is still among us)
