### ISSUE TITLE
invalid argument or something

### ISSUE THREAD

**Issue by jordikruit** [marnixah/japanese-asmr-parser#4]
broken 
[broken.txt](https://github.com/marnixah/japanese-asmr-parser/files/8146881/broken.txt)

**Comment by fredi-68** [comment]
thank you for your report!

**Comment by jordikruit** [comment]
getting this for all my downloads now, it worked for like 7 files and then it broke

**Comment by marnixah** [comment]
works on my machine

**Comment by marnixah** [comment]
skill issue
